public/index.html
Updated Title of app with `React App` to `bio-tree`
Fixes #3 
Please delete options that are not relevant.
=> Update title in  index.html

src/users/Kalyani2419.json
Updated Kalyani's Twitter Profile
=> Updated Kalyani's Twitter Profile

src/users/tejalsakore.json
- Added my profile to this repo
=> Added My Profile

src/users/Kalyani2419.json
Updated Kalyani's Instagram Profile
=> Updated Kalyani's Instagram Profile

src/users/Kalyani2419.json
Updated Kalyani's YouTube Profile
=> Updated Kalyani's YouTube Profile

src/users/tejalsakore.json
- Added my GitHub profile
- Added my LinkedIn profile
=> added my LinkedIn profile

src/users/Kalyani2419.json
Updated Kalyani's Facebook Profile
=> Updated Kalyani's Facebook Profile

src/users/Kalyani2419.json
Updated Kalyani's Hashnode Profile
=> Updated Kalyani's Hashnode Profile

src/users/tejalsakore.json
=> Added my Twitter profile

src/users/Abhishekgoel29.json
=> Added linkedin Profile

src/users/tejalsakore.json
=> Added my Insta profile

RaviYadav369
=> RaviYadav369.json

src/users/yashnaravade.json
=> Added my GitHub profile

src/users/tejalsakore.json
=> Added my bio

src/users/yashnaravade.json
=> Added LinkedIn  account

src/users/yashnaravade.json
=> Added Instagram account

src/users/Aryavardhan_Modi.json
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # (issue)
Please delete options that are not relevant.
- [] Any dependent changes have been merged and published in downstream modules
=> Aryavardhan's profile

src/users/cholinkol.json
Hello, i contribute myself into project :). Thanks for repo!
=> ✨ hello kevin!

src/users/CM-GoGo.json
Added youtube channel and account
=> Added Youtube channel

src/users/CM-GoGo.json
Added facebook account
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # (issue)
Please delete options that are not relevant.
=> Added facebook account

src/users/CM-GoGo.json
=> Added Twitter account

src/users/naravadey.json
=> Made my profile
